# Generated by Django 4.1.7 on 2023-06-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customuser_profile_customuser_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedio',
            new_name='Video',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='vedios',
            new_name='videos',
        ),
    ]
